<?php
$trans_mapping = array(
		'ap_icas_construction_review_date',
		'xx_1',
		'xx_2', 
		'xx_3',
		'ap_icas_cod_bazin_0',
		'ap_icas_cod_bazin_1',
		'ap_icas_cod_bazin_2',
		'ap_icas_cod_bazin_3',
		'ap_icas_cod_bazin_4',
		'ap_icas_cod_bazin_5',
		'ap_icas_cod_bazin_6',
		'ap_icas_basin_name',
		'ap_icas_construction_code_0',
		'ap_icas_construction_code_1',
		'xx_4',
		'xx_5',
		'ap_icas_construction_county',
		'ap_icas_construction_city',
		'ap_icas_construction_owner', //20
		
		'ap_icas_construction_longitude_deg',
		'ap_icas_construction_longitude_min',
		'ap_icas_construction_longitude_sec',
		
		'ap_icas_construction_latitude_deg',
		'ap_icas_construction_latitude_min',
		'ap_icas_construction_latitude_sec',
		
		'ap_icas_construction_date',
		
		'xx_6',
		'xx_7',
		'xx_8',
		
		'ap_icas_trans_dim_ye',
		'ap_icas_trans_dim_h',
		'ap_icas_trans_dim_a',
		'ap_icas_trans_dim_b',
		'trans_constr_type',
		'ap_icas_trans_dim_lr',
		'ap_icas_trans_dim_br',
		'trans_disip_type',
		'ap_icas_trans_dim_lc',
		'ap_icas_trans_dim_bc',
		
		'mat_main_body',
		'mat_wings',
		'mat_apron',
		'mat_counter_dam',
		'mat_side_walls',
		'mat_final_spur',
		
		'ap_icas_trans_damage_dec_left',
		'ap_icas_trans_damage_dec_right',
		'ap_icas_trans_damage_af_height',
		'ap_icas_trans_damage_af_percent',
		'ap_icas_trans_damage_h_crak_dev_nr',
		'ap_icas_trans_damage_h_crak_dev_l',
		'ap_icas_trans_damage_v_crak_dev_nr',
		'ap_icas_trans_damage_v_crak_dev_l',
		'ap_icas_trans_damage_h_crak_undev_nr',
		'ap_icas_trans_damage_h_crak_undev_l',
		'ap_icas_trans_damage_v_crak_undev_nr',
		'ap_icas_trans_damage_v_crak_undev_l',
		'ap_icas_trans_damage_detach_dev',		
		'ap_icas_trans_damage_detach_undev_left',
		'ap_icas_trans_damage_detach_undev_right',
		'ap_icas_trans_damage_erosion_height',
		'ap_icas_trans_damage_erosion_percent',
		
		'ap_icas_trans_apron_crack_nr',
		'ap_icas_trans_apron_crack_percent',
		'ap_icas_trans_apron_detach',
		'ap_icas_trans_apron_teeth_detach',
		'ap_icas_trans_apron_teeth_total',
		'ap_icas_trans_apron_detach_counter_dam',
		'ap_icas_trans_apron_erosion_percent',
		'ap_icas_trans_apron_erosion_height',
		
		
		'ap_icas_trans_sidewall_left_horiz_craks_nr',
		'ap_icas_trans_sidewall_left_horiz_length',
		'ap_icas_trans_sidewall_left_vert_craks_nr',
		'ap_icas_trans_sidewall_left_vert_length',
		'ap_icas_trans_sidewall_right_horiz_craks_nr',
		'ap_icas_trans_sidewall_right_horiz_length',
		'ap_icas_trans_sidewall_right_vert_craks_nr',
		'ap_icas_trans_sidewall_right_vert_length',		
		'ap_icas_trans_sidewall_left_displaced',
		'ap_icas_trans_sidewall_right_displaced',
		'ap_icas_trans_sidewall_left_abrasion_deep',
		'ap_icas_trans_sidewall_left_abrasion_percent',
		'ap_icas_trans_sidewall_right_abrasion_deep',
		'ap_icas_trans_sidewall_right_abrasion_percent',
		
		'xx_9', // exista pinten terminal?
		'xx_10',
		'ap_icas_trans_final_spur_decastr_left',
		'ap_icas_trans_final_spur_decastr_right',
		'ap_icas_trans_apron_af_height',
		'ap_icas_trans_apron_af_percent',		
		'ap_icas_trans_final_spur_horiz_crack_nr',
		'ap_icas_trans_final_spur_horiz_crack_length',
		'ap_icas_trans_final_spur_vert_crack_nr',
		'ap_icas_trans_final_spur_vert_crack_length',
		'ap_icas_trans_final_spur_detach_left',
		'ap_icas_trans_final_spur_detach_right',
		'ap_icas_trans_final_spur_detach_center',
		'ap_icas_trans_final_spur_erosion_height',
		'ap_icas_trans_final_spur_erosion_percent',
		
		'ap_icas_trans_disf_colmat_deversor',
		'ap_icas_trans_disf_colmat_apron_su',
		'ap_icas_trans_disf_colmat_apron_srad',
		'ap_icas_trans_disf_hat',
		'trans_gal_type',
		'ap_icas_trans_disf_veget_amonte',
		'ap_icas_trans_disf_veget_aval',
		'ap_icas_trans_disf_section_dim',
		
		'xx_11',
		'xx_12',
		'xx_13',
		'xx_14',
		'xx_15',
		'xx_16', // Observatii
		'xx_17',
		'xx_18',
		'xx_19',
		'xx_20',
		'xx_21',
		'xx_22',
		'xx_23',
		'xx_24',
		'xx_25',
		'xx_26',
		'xx_27',//Cauze apariţie disfuncţionalităţi
		'xx_28',
		'xx_29',
		'xx_30',
		'xx_31',
		'xx_32', // Stare
		'wwwww', // Grad îndepl. obiective ??? 
		'ap_icas_construction_ys'
		
);